# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.


In [13]:
# Assignment 1.1:
# Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
import pandas as pd
import numpy as np

# Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers
lst = np.random.randint(1, 100, size=(6,4))
print('Original DataFrame:')
print(lst)
df = pd.DataFrame(lst, columns=['a', 'b', 'c', 'd'])
print(df)

# Set the index to be the first column
df.set_index('a', inplace=True)
print('Dataframe with new index:')
print(df)

Original DataFrame:
[[65 22 99 86]
 [10 28 29 48]
 [42 71 30 83]
 [78 60 18 26]
 [51 20 53 93]
 [82 14 71 99]]
    a   b   c   d
0  65  22  99  86
1  10  28  29  48
2  42  71  30  83
3  78  60  18  26
4  51  20  53  93
5  82  14  71  99
Dataframe with new index:
     b   c   d
a             
65  22  99  86
10  28  29  48
42  71  30  83
78  60  18  26
51  20  53  93
82  14  71  99


In [21]:
# Assingment 1.2:
# Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(1,10, size=(3,3)), columns=('A', 'B', 'C'), index=('X', 'Y', 'Z'))
print(df)
print('\n')
print(df.at['Y', 'B'])

   A  B  C
X  8  8  6
Y  1  8  6
Z  5  2  9


8


In [26]:
# Assignment 2.1:
# Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(1,10, size=(5,3)), columns=('a', 'b', 'c'))
print(df)

print('\n New "d" column added: ')
df['d'] = df['a'] * df['b']
print(df)

   a  b  c
0  8  7  5
1  3  6  2
2  5  8  9
3  1  7  3
4  3  3  9

 New "d" column added: 
   a  b  c   d
0  8  7  5  56
1  3  6  2  18
2  5  8  9  40
3  1  7  3   7
4  3  3  9   9


In [40]:
# Assignment 2.2: 
# Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(1,10, size=(4,3)), columns=('a', 'b', 'c'))
print(df)

   a  b  c
0  2  1  4
1  6  5  1
2  3  6  8
3  3  8  2


In [7]:
# Assignment 3.1:
# Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(1,10, size=(5,3)), columns=('a', 'b', 'c'))
df.iloc[0, 1] = np.nan
df.iloc[2, 2] = np.nan
df.iloc[4, 0] = np.nan
print(df)

# fill missing values
df.fillna(df.mean(), inplace=True)
print(df)

     a    b    c
0  3.0  NaN  8.0
1  8.0  8.0  9.0
2  2.0  3.0  NaN
3  7.0  2.0  7.0
4  NaN  9.0  1.0
     a    b     c
0  3.0  5.5  8.00
1  8.0  8.0  9.00
2  2.0  3.0  6.25
3  7.0  2.0  7.00
4  5.0  9.0  1.00


In [17]:
# Assignment 3.2:
# Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(1,10, size=(6,4)))
df.at[0,1] = np.nan
df.at[3,0] = np.nan
df.at[2,2] = np.nan
print("DataFrame with NaN values:")
print(df, '\n')

df.dropna(inplace=True)
print("DataFrame with NaN values dropped:")
print(df)

DataFrame with NaN values:
     0    1    2  3
0  9.0  NaN  9.0  5
1  8.0  6.0  5.0  3
2  1.0  4.0  NaN  9
3  NaN  2.0  6.0  6
4  5.0  9.0  9.0  9
5  6.0  9.0  8.0  3 

DataFrame with NaN values dropped:
     0    1    2  3
1  8.0  6.0  5.0  3
4  5.0  9.0  9.0  9
5  6.0  9.0  8.0  3


In [39]:
# Assignment 4.1:
# Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. 
# Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. 
# Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

import pandas as pd
import numpy as np

lst = ['A', 'B', 'C']
df = pd.DataFrame({'Category': np.random.choice(['A','B','C'], size=10), 'Value': np.random.randint(1,10, size=10)})
df

,Category:,Value:
0,C,8
1,C,6
2,C,8
3,C,7
4,A,3
5,C,9
6,B,5
7,C,3
8,B,8
9,A,2
